### ISSUE TITLE
EPIC || NEW MODEL

### ISSUE THREAD

**Issue by eemshi** [codefordenver/owlet#377]
- [x] Add tag data to activities via tagRef
- [x] Add branch data to activities via branchRef
- [x] Fix search functionality
- [x] Fix tags in activity-thumbnail
